[package]
name = "console-editr"
version = "0.1.0"
edition = "2021"
authors = ["AnvayPatil"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
unicode-segmentation = "1"
